name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add src to PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV

      - name: Prepare test project environment
        run: |
          mkdir tests/test_outputs
          cd tests/test_outputs
          python spp_cli.py init
          cd ../..

      - name: Run unit tests
        run: |
          python -m unittest discover tests
